version: "3.1"
services:
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html
            - ./vendor:/home/vendor/
        networks:
            - default
volumes:
    persistent:
